// Default labor and material items pre-loaded from the SPK spreadsheet structure

export const DEFAULT_SPRINKLER_LABOR_ITEMS = [
  // Automated Labor items from SPK sheets
  { item: "SPRINKLER HEADS", quantity: 0, factor: 0.5, total: 0, is_manual: false },
  { item: "1\" PIPE (LF)", quantity: 0, factor: 0.05, total: 0, is_manual: false },
  { item: "1¼\" PIPE (LF)", quantity: 0, factor: 0.06, total: 0, is_manual: false },
  { item: "1½\" PIPE (LF)", quantity: 0, factor: 0.07, total: 0, is_manual: false },
  { item: "2\" PIPE (LF)", quantity: 0, factor: 0.08, total: 0, is_manual: false },
  { item: "2½\" PIPE (LF)", quantity: 0, factor: 0.10, total: 0, is_manual: false },
  { item: "3\" PIPE (LF)", quantity: 0, factor: 0.12, total: 0, is_manual: false },
  { item: "4\" PIPE (LF)", quantity: 0, factor: 0.15, total: 0, is_manual: false },
  { item: "6\" PIPE (LF)", quantity: 0, factor: 0.20, total: 0, is_manual: false },
  { item: "HANGERS", quantity: 0, factor: 0.25, total: 0, is_manual: false },
  { item: "SEISMIC BRACING", quantity: 0, factor: 0.75, total: 0, is_manual: false },
  { item: "THREADED FITTINGS", quantity: 0, factor: 0.20, total: 0, is_manual: false },
  { item: "GROOVED FITTINGS", quantity: 0, factor: 0.35, total: 0, is_manual: false },
  { item: "WELDED FITTINGS", quantity: 0, factor: 0.50, total: 0, is_manual: false },
  { item: "VALVES", quantity: 0, factor: 0.75, total: 0, is_manual: false },
  { item: "RISER ASSEMBLY", quantity: 0, factor: 4.0, total: 0, is_manual: false },
  { item: "BACKFLOW PREVENTER", quantity: 0, factor: 8.0, total: 0, is_manual: false },
  { item: "INSPECTOR TEST CONNECTION", quantity: 0, factor: 2.0, total: 0, is_manual: false },
  { item: "FLOW SWITCH", quantity: 0, factor: 1.5, total: 0, is_manual: false },
  { item: "TAMPER SWITCH", quantity: 0, factor: 1.0, total: 0, is_manual: false },
  { item: "GAUGE", quantity: 0, factor: 0.5, total: 0, is_manual: false },
  { item: "DRAIN", quantity: 0, factor: 0.75, total: 0, is_manual: false },
  { item: "ALARM CHECK VALVE", quantity: 0, factor: 6.0, total: 0, is_manual: false },
  { item: "VERTICAL RISER PIPE (LF)", quantity: 0, factor: 0.20, total: 0, is_manual: false },
  { item: "HOISTING / VERTICAL DIST", quantity: 0, factor: 1.0, total: 0, is_manual: false },
];

export const DEFAULT_SPRINKLER_MATERIAL_ITEMS = [
  { item: "PIPE SCH 40 1\"", quantity: 0, price: 1.92, total: 0 },
  { item: "PIPE SCH 40 1¼\"", quantity: 0, price: 2.60, total: 0 },
  { item: "PIPE SCH 40 1½\"", quantity: 0, price: 3.11, total: 0 },
  { item: "PIPE SCH 40 2\"", quantity: 0, price: 4.18, total: 0 },
  { item: "PIPE SCH 40 2½\"", quantity: 0, price: 6.48, total: 0 },
  { item: "PIPE SCH 40 3\"", quantity: 0, price: 9.50, total: 0 },
  { item: "PIPE SCH 40 4\"", quantity: 0, price: 14.00, total: 0 },
  { item: "PIPE SCH 40 6\"", quantity: 0, price: 24.00, total: 0 },
  { item: "SPRINKLER HEAD - CONCEALED", quantity: 0, price: 8.50, total: 0 },
  { item: "SPRINKLER HEAD - PENDANT", quantity: 0, price: 4.50, total: 0 },
  { item: "SPRINKLER HEAD - UPRIGHT", quantity: 0, price: 4.25, total: 0 },
  { item: "SPRINKLER HEAD - SIDEWALL", quantity: 0, price: 5.50, total: 0 },
  { item: "HANGER W/TBC 1\"-2\"", quantity: 0, price: 7.01, total: 0 },
  { item: "HANGER W/TBC 2½\"-4\"", quantity: 0, price: 9.50, total: 0 },
  { item: "SEISMIC BRACE ASSEMBLY", quantity: 0, price: 45.00, total: 0 },
  { item: "ELBOW 1\" THREADED", quantity: 0, price: 0.75, total: 0 },
  { item: "TEE 1\" THREADED", quantity: 0, price: 1.00, total: 0 },
  { item: "COUPLING 2\" GROOVED", quantity: 0, price: 6.50, total: 0 },
  { item: "ELBOW 2\" GROOVED", quantity: 0, price: 7.25, total: 0 },
  { item: "TEE 2\" GROOVED", quantity: 0, price: 9.00, total: 0 },
  { item: "OS&Y VALVE 4\"", quantity: 0, price: 185.00, total: 0 },
  { item: "OS&Y VALVE 6\"", quantity: 0, price: 285.00, total: 0 },
  { item: "BUTTERFLY VALVE 4\"", quantity: 0, price: 125.00, total: 0 },
  { item: "CHECK VALVE 4\"", quantity: 0, price: 150.00, total: 0 },
  { item: "FLOW SWITCH", quantity: 0, price: 95.00, total: 0 },
  { item: "TAMPER SWITCH", quantity: 0, price: 65.00, total: 0 },
  { item: "PRESSURE GAUGE", quantity: 0, price: 25.00, total: 0 },
  { item: "INSPECTOR TEST CONN", quantity: 0, price: 45.00, total: 0 },
  { item: "DRAIN VALVE 2\"", quantity: 0, price: 18.00, total: 0 },
  { item: "ALARM CHECK VALVE 4\"", quantity: 0, price: 650.00, total: 0 },
  { item: "BACKFLOW PREVENTER 4\"", quantity: 0, price: 950.00, total: 0 },
  { item: "BACKFLOW PREVENTER 6\"", quantity: 0, price: 1450.00, total: 0 },
];

export const DEFAULT_STANDPIPE_LABOR_ITEMS = [
  { item: "2½\" PIPE (LF)", quantity: 0, factor: 0.10, total: 0, is_manual: false },
  { item: "3\" PIPE (LF)", quantity: 0, factor: 0.12, total: 0, is_manual: false },
  { item: "4\" PIPE (LF)", quantity: 0, factor: 0.15, total: 0, is_manual: false },
  { item: "6\" PIPE (LF)", quantity: 0, factor: 0.20, total: 0, is_manual: false },
  { item: "HANGERS", quantity: 0, factor: 0.35, total: 0, is_manual: false },
  { item: "SEISMIC BRACING", quantity: 0, factor: 0.75, total: 0, is_manual: false },
  { item: "GROOVED FITTINGS 2½\"", quantity: 0, factor: 0.40, total: 0, is_manual: false },
  { item: "GROOVED FITTINGS 3\"", quantity: 0, factor: 0.50, total: 0, is_manual: false },
  { item: "GROOVED FITTINGS 4\"", quantity: 0, factor: 0.65, total: 0, is_manual: false },
  { item: "GROOVED FITTINGS 6\"", quantity: 0, factor: 0.85, total: 0, is_manual: false },
  { item: "FDC CONNECTION", quantity: 0, factor: 4.0, total: 0, is_manual: false },
  { item: "HOSE VALVE 2½\"", quantity: 0, factor: 1.5, total: 0, is_manual: false },
  { item: "PRV ASSEMBLY", quantity: 0, factor: 6.0, total: 0, is_manual: false },
  { item: "PRESSURE GAUGE", quantity: 0, factor: 0.5, total: 0, is_manual: false },
  { item: "RISER / VALVE ASSEMBLY", quantity: 0, factor: 8.0, total: 0, is_manual: false },
];

export const DEFAULT_STANDPIPE_MATERIAL_ITEMS = [
  { item: "PIPE SCH 40 2½\"", quantity: 0, price: 6.48, total: 0 },
  { item: "PIPE SCH 40 3\"", quantity: 0, price: 9.50, total: 0 },
  { item: "PIPE SCH 40 4\"", quantity: 0, price: 14.00, total: 0 },
  { item: "PIPE SCH 40 6\"", quantity: 0, price: 24.00, total: 0 },
  { item: "COUPLING 2½\" GROOVED", quantity: 0, price: 9.50, total: 0 },
  { item: "ELBOW 2½\" GROOVED", quantity: 0, price: 11.00, total: 0 },
  { item: "TEE 2½\" GROOVED", quantity: 0, price: 14.00, total: 0 },
  { item: "COUPLING 4\" GROOVED", quantity: 0, price: 16.00, total: 0 },
  { item: "ELBOW 4\" GROOVED", quantity: 0, price: 21.00, total: 0 },
  { item: "TEE 4\" GROOVED", quantity: 0, price: 28.00, total: 0 },
  { item: "HANGER 2½\"-4\"", quantity: 0, price: 9.50, total: 0 },
  { item: "HOSE VALVE 2½\"", quantity: 0, price: 95.00, total: 0 },
  { item: "FDC SIAMESE CONN", quantity: 0, price: 285.00, total: 0 },
  { item: "OS&Y VALVE 4\"", quantity: 0, price: 185.00, total: 0 },
  { item: "CHECK VALVE 4\"", quantity: 0, price: 150.00, total: 0 },
  { item: "PRV 2½\"", quantity: 0, price: 285.00, total: 0 },
  { item: "PRESSURE GAUGE", quantity: 0, price: 25.00, total: 0 },
];